source ~/.vim/typos
source ~/.vim/defaults
source ~/.vim/syntax_hl
source ~/.vim/statusline
source ~/.vim/functions
source ~/.vim/autocmd
source ~/.vim/mappings

" vim:syntax=vim sw=4 ts=4 expandtab

